### ISSUE TITLE
Allow for custom cgitrc

### ISSUE THREAD

**Issue by GilOliveira** [joseluisq/alpine-cgit#7]
Not all of the `cgitrc` settings can be set using environment variables ([reference](https://linux.die.net/man/5/cgitrc)), and the file gets overwritten on startup if a custom `cgitrc` is binded to `/etc/cgitrc`. It would be very helpful if there were a way to specify a custom `cgitrc` file.

**Comment by joseluisq** [comment]
Done.

A new Docker Hub image update will be come in next hours.

**Comment by GilOliveira** [comment]
> Done.
> 
> A new Docker Hub image update will be come in next hours.

Thank you so much! This is going to be very useful, indeed!

**Comment by joseluisq** [comment]
Released on [v2.0.0](https://github.com/joseluisq/alpine-cgit/releases/tag/v2.0.0)
